services:
  - type: web
    name: thub-innovation
    env: node
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: SKIP_MIGRATIONS
        value: true
      - key: LIMIT_ACTIVE_SESSIONS
        value: true
      - key: EMAIL_USER
        value: info@t-hub.so
      - key: EMAIL_HOST
        value: mail.t-hub.so
      - key: EMAIL_PORT
        value: 465
      - key: EMAIL_SECURE
        value: true
      - key: EMAIL_PASSWORD
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: thub_db
          property: connectionString

databases:
  - name: thub_db
    plan: free 